# Generated by Django 4.0.4 on 2022-05-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_revenue_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='parkingDuration',
            field=models.DurationField(null=True),
        ),
    ]
