# Generated by Django 4.0.4 on 2022-05-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_parking_user_alter_revenue_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='entryTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='parkingDuration',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
