# Generated by Django 4.0.4 on 2022-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_revenue_date_alter_revenue_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parkingsAvailable',
            field=models.PositiveBigIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='parkingsVacant',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
