# Generated by Django 4.0.4 on 2022-05-20 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_parking_parkingsavailable_parking_parkingsvacant'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
