# Generated by Django 4.0.4 on 2022-05-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_parking_type_alter_parking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='type',
            field=models.CharField(default='car', max_length=15),
            preserve_default=False,
        ),
    ]
